<template>
  <div class="loadingio-spinner-chunk-04f652uyzbu2">
    <div class="ldio-29patholaao">
      <div>
        <div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
</template>
<style>
@keyframes ldio-29patholaao-r {
  0%,
  25%,
  50%,
  75%,
  100% {
    animation-timing-function: cubic-bezier(0, 1, 0, 1);
  }
  0% {
    transform: scale(0.75) rotate(180deg);
  }
  25% {
    transform: scale(0.75) rotate(270deg);
  }
  50% {
    transform: scale(0.75) rotate(360deg);
  }
  75% {
    transform: scale(0.75) rotate(450deg);
  }
  100% {
    transform: scale(0.75) rotate(540deg);
  }
}
@keyframes ldio-29patholaao-z {
  0%,
  50%,
  100% {
    animation-timing-function: cubic-bezier(1, 0, 0, 1);
  }
  0% {
    transform: scale(1);
  }
  50% {
    transform: scale(1);
  }
  100% {
    transform: scale(0.5);
  }
}
@keyframes ldio-29patholaao-p {
  0%,
  50%,
  100% {
    animation-timing-function: cubic-bezier(1, 0, 0, 1);
  }
  0% {
    transform: scale(0);
  }
  50% {
    transform: scale(1);
  }
  100% {
    transform: scale(1);
  }
}
@keyframes ldio-29patholaao-c {
  0%,
  25%,
  50%,
  75%,
  100% {
    animation-timing-function: cubic-bezier(0, 1, 0, 1);
  }
  0% {
    background: #3c0f0f;
  }
  25% {
    background: #f91a10;
  }
  50% {
    background: #e46b43;
  }
  75% {
    background: #edb195;
  }
  100% {
    background: #3c0f0f;
  }
}
.ldio-29patholaao > div {
  animation: ldio-29patholaao-r 4s linear infinite;
  transform-origin: 50px 50px;
}
.ldio-29patholaao > div > div {
  width: 100px;
  height: 100px;
  position: absolute;
  animation: ldio-29patholaao-z 1s linear infinite;
  transform-origin: 100px 100px;
}
.ldio-29patholaao > div > div div {
  position: absolute;
  width: 50px;
  height: 50px;
  background: #3c0f0f;
  transform-origin: 25px 25px;
}
.ldio-29patholaao > div > div div:nth-child(1) {
  left: 0px;
  top: 0px;
  animation: ldio-29patholaao-p 1s linear infinite,
    ldio-29patholaao-c 4s linear infinite;
}
.ldio-29patholaao > div > div div:nth-child(2) {
  left: 50px;
  top: 0px;
  animation: ldio-29patholaao-p 1s linear infinite,
    ldio-29patholaao-c 4s linear infinite;
}
.ldio-29patholaao > div > div div:nth-child(3) {
  left: 0px;
  top: 50px;
  animation: ldio-29patholaao-p 1s linear infinite,
    ldio-29patholaao-c 4s linear infinite;
}
.ldio-29patholaao > div > div div:nth-child(4) {
  left: 50px;
  top: 50px;
  transform: scale(1);
  animation: ldio-29patholaao-c 4s linear infinite;
}
.loadingio-spinner-chunk-04f652uyzbu2 {
  width: 80px;
  height: 80px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-29patholaao {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.8);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-29patholaao div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>